### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by mohammadayn** [manuelernestog/weektodo#162]
Hi
The app icons in top of it and the windows taskbar are different with the actual app icon.

![Screenshot_20221224_121732](https://user-images.githubusercontent.com/10381709/209428418-2dc9d3f2-6ae3-4e9c-95e7-00b8f2808c0e.png)

**Comment by manuelernestog** [comment]
Hi @mohammadayn thanks for reporting this. It's look like a bug in the last release for Windows. I'll take a look :+1:

**Comment by manuelernestog** [comment]
Thanks @abdallahkorraim What version of the app did you install? I'm using the .dev app and it's look ok

**Comment by abdallahkorraim** [comment]
@manuelernestog  the latest release in the snap store, which is 2.0.0

**Comment by manuelernestog** [comment]
Ok Thanks fro the feedback @abdallahkorraim I'll take a look ASAP

**Comment by manuelernestog** [comment]
Can anyone please confirm if this problem was fixed on version 2.1.0 It's really hard for me to test this in all OS.
 
 @not-matthias  @abdallahkorraim  @mohammadayn

**Comment by mohammadayn** [comment]
> Can anyone please confirm if this problem was fixed on version 2.1.0 It's really hard for me to test this in all OS.
Hi
I installed the last version on Windows and the issue was fixed.
Thanks @manuelernestog

**Comment by manuelernestog** [comment]
Great! Thanks for the feedback @mohammadayn 👍️
