### ISSUE TITLE
Feature Request: running the app on docker

### ISSUE THREAD

**Issue by GaetanoEsse** [manuelernestog/weektodo#176]
It would be great if we can self host the app on a docker container, solving the syncing problem betweek devices temporarely

**Comment by manuelernestog** [comment]
Hi @GaetanoEsse thanks for the suggestion. For now weektodo just run in the client side and the idea is trying to find the sync using  clouds services like google  drive, onwcloud or something like this. Using docker, looks like an overkill solution to run an electron app and it would be very complicated to use by a common user.
