### ISSUE TITLE
[feature request] task in progress pane

### ISSUE THREAD

**Issue by ihubgit** [manuelernestog/weektodo#177]
Hi,
currently the app only distinguishes between a bottom part (personal to do categories) and an upper part (calendar).
It seems to me an intermediate pane is lacking for the tasks in progress.
It could be similar to the bottom part, i.e. allowing for keeping tasks according to their categories, but distinguishing them from the to-dos on the one hand and the completed items on the other hand.
One should be able to track progress on a given task f.ex. in a notes section for those notes.

**Comment by manuelernestog** [comment]
Hello @ihubgit , thanks for writing and for the feedback.

I really think that a task panel in development nomache matches very well with the design of the app. In the end, everyone can use it in their own way, but the way it is designed is to carry the tasks that are being carried out in the calendar view, agendas by days and the list below would serve as a drawer for other tasks that are being stored. . In case you want to manage statuses such as pending, in progress or done, you can do it like a kanbam board using the same columns. 

Something like this
![image](https://github.com/manuelernestog/weektodo/assets/53962116/1d777e0e-8cbb-44f5-994a-de184ca34ee9)

Regards
