### ISSUE TITLE
[feature request] task title spreading over one line

### ISSUE THREAD

**Issue by ihubgit** [manuelernestog/weektodo#178]
Hi,
it would be nice to be able to see the whole of a task's title in one's personal categories.
Currently, it's visibility is clipped when running over a single line which makes me have to click on it to be able to see everything.
Why not allowong for a task to take as much lines it needs (2, 3) so one can see immediately what the task is about ?

**Comment by Xezarior** [comment]
Hi @ihubgit ,

I believe that the feature you are requesting is already implemented.
Have you tried deactivating the _Compact Mode_ in settings? (Settings cog -> Display -> Compact View)
