### ISSUE TITLE
[Bug] Setting a markdown link in the task notes section will open the link in the app itself

### ISSUE THREAD

**Issue by SaifEl-Deen** [manuelernestog/weektodo#181]
Bug:
Setting a markdown link in the task notes section will open the link in the app itself when clicking on that link

Description:
1. Type [random text](random link) into the notes section of a task
2. Save
3. Click on the link **random text**
4. The link will open in the app itself instead of using the browser

Solution:
Set the links to open externally in the default browser

**Comment by manuelernestog** [comment]
Fixed. Will be released on v2.1.0
