### ISSUE TITLE
[Potentially unwanted behaviour] Do not automatically reorder subtasks when done

### ISSUE THREAD

**Issue by Xezarior** [manuelernestog/weektodo#183]
(Desktop-App on Windows 11)

I have deactivated both options "automatically reorder tasks" and "move done tasks to the bottom", but this does not affect sub-tasks.

When I complete a sub-task, it gets moved to the bottom, with another task taking it's place below my cursor.
I find this behavior not desirable and would like to be able to deactivate it. It forces me to always be careful when ticking off multiple sub-tasks at once, as I cannot expect them to be where I intended to click.

**Comment by manuelernestog** [comment]
I'll take a look at this. I think I implemented in tasks but not in subtasks 👌

**Comment by manuelernestog** [comment]
Done! Now we have a new setting to move the subtasks to the bottom.
Will be deployed on v2.1.0
![image](https://github.com/manuelernestog/weektodo/assets/53962116/a94fe6b9-06db-4799-852c-986d9d94334a)

**Comment by Xezarior** [comment]
Thank you very much! This will make completing sub-tasks a lot more rewarding for me!

**Comment by manuelernestog** [comment]
Thanks for the feedback @Xezarior happy to help :)
