### ISSUE TITLE
[Potentially unwanted behavior] Reminders: do not notify about tasks that are already done

### ISSUE THREAD

**Issue by Xezarior** [manuelernestog/weektodo#184]
(Desktop-App on Windows 11)

I have some recurring tasks to remind me of doing specific things on certain days, with a reminder set as fail-safe, should I happen to forget about them.
However, if I complete those tasks (including all sub-tasks) before the time of the reminder, I still get a notification at the set time of the task.

I would like to be able to not receive notifications for already-completed tasks.

**Comment by manuelernestog** [comment]
Hello Zenior, thanks for reporting that, now I have a look at the code, I am almost sure that I had implemented it this way but I imagine that something is wrong.

**Comment by manuelernestog** [comment]
Fixed! Will be introduced in v2.1.0
