### ISSUE TITLE
[FR] Pressing Esc button to quit he task editing window

### ISSUE THREAD

**Issue by SaifEl-Deen** [manuelernestog/weektodo#188]
Simply when I edit a task, I find it easier to press the Esc button to quit the task editing window after I'm finished with modifying this task.

**Comment by manuelernestog** [comment]
Are you referring to the details modal ?

**Comment by SaifEl-Deen** [comment]
I meant this:
![image](https://github.com/manuelernestog/weektodo/assets/130001839/137059be-3887-4b45-ac3c-52115401feca)

**Comment by manuelernestog** [comment]
Done. Will be out in v2.1
