### ISSUE TITLE
Task Font

### ISSUE THREAD

**Issue by thereallgoingtolaughatyou** [manuelernestog/weektodo#195]
Add ability to pick out font or maybe use plus and minus/shift buttons to increase decrease size to be able to see more on task lines for longer worded tasks.

**Comment by manuelernestog** [comment]
You can't achieve a similar effect using the zoom button or are you looking for something else?

Just to have some context and get an idea, in what resolution are you viewing the app that looks so small?

**Comment by thereallgoingtolaughatyou** [comment]
Hi,

I am using the desktop application in Windows.  I didn't see a way to zoom in our out.  I know you can see more text if you reduce the columns/number of days.  I was looking to either change the font size in settings so I could see more text or maybe have a way to use the shift and plus/minus to zoom and out?  I wasn't sure what the standard way to accomplish this is, but maybe I am missing a way to do it that already exists in the application.

**Comment by manuelernestog** [comment]
If you open settings in the display tab you have a Zoom option. Please let me know if you don't see it in your app. Sadly this cross platform approach is nice, but I have a lot of report of inconsistencies depends on the system :(

![image](https://github.com/manuelernestog/weektodo/assets/53962116/8fed7d97-a21a-457b-9b6e-29dfa86457a1)

**Comment by thereallgoingtolaughatyou** [comment]
Thank you...it was right there the whole time and works great.
