### ISSUE TITLE
support for synchronization

### ISSUE THREAD

**Issue by gugu-py** [manuelernestog/weektodo#199]
Is there any ways to sychronize the files(tasks) between devices?
Where is the tasks file stored?

**Comment by manuelernestog** [comment]
Hi @gugu-py I have to work on this feature for do it native but for now you can use https://syncthing.net/

The data is stored in different folder depending on your OS.

Mac OS: ~/weektodo/Application Support/<Your App Name (taken from the name property in package.json)>
Windows: C:\Users\<you>\AppData\Local\weektodo
Linux: ~/.config/weektodo

**Comment by gugu-py** [comment]
thank you!
