### ISSUE TITLE
[Feature Request] - Option to choose default sound device

### ISSUE THREAD

**Issue by MatteCrystal** [manuelernestog/weektodo#205]
I have my headphones always plugged in but I'm not always waring them. It would be nice if I could set the default audio device to my pc speakers instead of whatever is selected in windows as default. That way I can hear alarms more often.

**Comment by manuelernestog** [comment]
Hi @MatteCrystal this is a very specific case use, I think windows have a menu to select the device used for each app, and if not there are some third party apps for that, I think you can fix that problem with that.
