### ISSUE TITLE
[Feature Request]  - Create recurring activity

### ISSUE THREAD

**Issue by devalexandre** [manuelernestog/weektodo#206]
create a recurring task, being able to activate the task for every day at the same time as the original task, and you can also set it weekly, monthly, and you can enable it if you want to run it on weekends as well

**Comment by bonirin** [comment]
Is there a way to remove them?

**Comment by manuelernestog** [comment]
Hi @devalexandre you can recurrent task in the details of the tasks. Just set a time and then enable the recurrint taks.
![image](https://github.com/manuelernestog/weektodo/assets/53962116/b4760398-8b9d-448b-b251-1c6d403e2a93)
